name: selenium_sign_in

on:
  schedule:
    - cron: '0 9 * * *' # 每天 UTC 时间 00:00 执行
  push: # 每次 push 时执行
  workflow_dispatch:

jobs:
  sign_in_job:
    env:
      USER_NAME: ${{ secrets.USER_NAME }}
      USER_PWD: ${{ secrets.USER_PWD }}
      BOT_OPEN: ${{ secrets.BOT_OPEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: Set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      - name: Checkout Repository
        uses: actions/checkout@v4 # 检出您的代码
        with:
          ref: selenium_impl

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5' # 选择 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run sign in script
        run: python src/daily_sign.py
