name: Daily Sign-in

on:
  schedule:
    - cron: '0 9 * * *' # 每天 UTC 时间 00:00 执行
  push: # 每次 push 时执行
  workflow_dispatch:

jobs:
  sign_in_job:
    runs-on: ubuntu-latest # 运行环境

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # 检出您的代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5' # 选择 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Some step
      run: echo "Setup env variables here"  # 这只是一个占位符
      env: # 设置环境变量
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PWD: ${{ secrets.USER_PWD }}
        BOT_OPEN: ${{ secrets.BOT_OPEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
    - name: Run sign in script
      run: python auto_sign_in.py # 执行您的 Python 脚本
